FROM node:20-alpine

WORKDIR /app

# Install package co trong package.json
COPY package*.json ./

RUN npm install

#Copy may cai khac
COPY  . .

#Expose Nextjs dev port
EXPOSE 3000

#Run in dev mode (Turbopack enabled (Nextjs))
CMD [ "npm", "run", "dev" ]